root: true
env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-recommended
  - standard-with-typescript
  - prettier
  - plugin:prettier/recommended
parser: vue-eslint-parser
parserOptions:
  extraFileExtensions:
    - .vue
  parser: "@typescript-eslint/parser"
  project:
    - tsconfig.json
    - tsconfig.node.json
globals:
  TGApp: readonly
  window: readonly
plugins:
  - vue
  - prettier
rules:
  # normal
  array-callback-return: warn
  # TypeScript
  "@typescript-eslint/strict-boolean-expressions": off
  "@typescript-eslint/consistent-type-assertions":
    - warn
    - assertionStyle: angle-bracket # 使用尖括号
  "@typescript-eslint/naming-convention":
    - warn
    - selector: variableLike
      format: ["camelCase", "UPPER_CASE", "PascalCase", "snake_case"]
      leadingUnderscore: "allow"
      trailingUnderscore: "allow"
  "@typescript-eslint/no-non-null-assertion": warn
  # Vue
  "vue/multi-word-component-names": off
