root: true
env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-recommended
  - standard-with-typescript
  - prettier
  - plugin:prettier/recommended
parser: vue-eslint-parser
parserOptions:
  extraFileExtensions:
    - .vue
  parser: "@typescript-eslint/parser"
  project:
    - tsconfig.json
    - tsconfig.node.json
globals:
  TGApp: readonly
plugins:
  - vue
  - prettier
rules:
  # 严格布尔表达式
  "@typescript-eslint/strict-boolean-expressions": off
  # 禁止使用 Object
  "@typescript-eslint/consistent-type-assertions":
    - warn
    - assertionStyle: angle-bracket # 使用尖括号
  # 命名规范
  "@typescript-eslint/naming-convention":
    - warn
    - selector: variableLike
      format: ["camelCase", "UPPER_CASE", "PascalCase", "snake_case"]
      leadingUnderscore: "allow"
      trailingUnderscore: "allow"
