extends:
  - stylelint-high-performance-animation
  - stylelint-order
  - stylelint-declaration-block-no-ignored-properties
  - stylelint-config-standard-vue
plugins:
  - stylelint-prettier
rules:
  "prettier/prettier": true
