name: Publish Release
on:
  push:
    tags:
      - v*

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.2
      - name: Install frontend dependencies
        run: pnpm install

      - name: Build app
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        #          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: v__VERSION__-beta
          releaseBody: |
            > 建议通过微软应用商店下载，此处仅作为备份

            <a href="https://apps.microsoft.com/store/detail/9NLBNNNBNSJN?launch=true&cid=BTMuli&mode=mini">
              <img src="https://get.microsoft.com/images/zh-cn%20dark.svg" alt="download"/>
            </a>
          releaseDraft: true
          prerelease: false
